target: kamratMerge kamratReduce kamratNorm kamratMask

kamratMerge: kamratMerge.cpp data_struct/count_tab_header.cpp data_struct/count_tab.cpp data_struct/seq_elem.cpp data_struct/contig_elem.cpp data_struct/merge_knot.cpp
	g++ -o ../bin/kamratMerge kamratMerge.cpp data_struct/count_tab_header.cpp data_struct/count_tab.cpp data_struct/seq_elem.cpp data_struct/contig_elem.cpp data_struct/merge_knot.cpp

kamratReduce: kamratReduce.cpp utils/sample_info.cpp reduce/model_info.cpp
	g++ -o ../bin/kamratReduce kamratReduce.cpp utils/sample_info.cpp reduce/model_info.cpp -fopenmp -lmlpack -larmadillo -I/path_to_conda_mlpack_env/include

kamratNorm: kamratNorm.cpp data_struct/count_tab_header.cpp data_struct/sample_info.cpp 
	g++ -o ../bin/kamratNorm kamratNorm.cpp data_struct/count_tab_header.cpp data_struct/sample_info.cpp -lboost_iostreams

kamratMask: kamratMask.cpp
	g++ -o ../bin/kamratMask kamratMask.cpp

